version: '3'

services:
  pg:
    image: postgres:15-alpine3.20
    environment:
      - "POSTGRES_DB=${DB_DATABASE_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7.2.5-alpine3.20
    ports:
      - "6379:6379"

  # migrator:
  #   build:
  #     context: .
  #     dockerfile: migration.Dockerfile
  #   restart: on-failure
  #   environment:
  #     DB_HOST: pg

  rabbitmq:
    image: rabbitmq:4.0.3-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672